/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface JobQueries {
  createdAt: Generated<Timestamp>;
  cronInterval: string;
  experienceLevel: Generated<string[]>;
  id: Generated<string>;
  position: string;
  startAt: string;
  timeframePosted: string;
  updatedAt: Generated<Timestamp>;
  workplaceType: Generated<string[]>;
}

export interface Jobs {
  applicantsCount: string;
  companyLink: string;
  companyName: string;
  createdAt: Generated<Timestamp>;
  date: string;
  description: string;
  id: Generated<string>;
  jobQueryId: string;
  link: string;
  location: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  jobQueries: JobQueries;
  jobs: Jobs;
  users: Users;
}
