/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accountId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  password: string | null;
  providerId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface JobQueries {
  createdAt: Generated<Timestamp>;
  cronInterval: string;
  experienceLevel: Generated<string[]>;
  id: Generated<string>;
  position: string;
  startAt: string;
  timeframePosted: string;
  updatedAt: Generated<Timestamp>;
  workplaceType: Generated<string[]>;
}

export interface LeadQueries {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  keyword: string;
  location: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  value: string | null;
  verificationType: string;
}

export interface DB {
  accounts: Accounts;
  jobQueries: JobQueries;
  leadQueries: LeadQueries;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
