/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccessRequestStatus = "approved" | "pending" | "rejected";

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[];

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type InviteStatus = "accepted" | "expired" | "pending" | "revoked";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "member";

export type VerificationType = "email_change" | "password_reset";

export interface AccessRequests {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  reviewedBy: string | null;
  status: Generated<AccessRequestStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface Accounts {
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  password: string | null;
  providerId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Invites {
  accessRequestId: string;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  name: string;
  roles: Generated<ArrayType<UserRole>>;
  status: Generated<InviteStatus>;
  token: string;
  updatedAt: Generated<Timestamp>;
}

export interface LeadQueries {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  keyword: string;
  location: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Leads {
  address: string | null;
  auditDiagnosis: string[] | null;
  companyName: string;
  completionStatus: Generated<string>;
  createdAt: Generated<Timestamp>;
  emailDraft: Json | null;
  emails: string[] | null;
  id: Generated<string>;
  leadQueryId: string;
  mapLink: string;
  phone: string | null;
  updatedAt: Generated<Timestamp>;
  website: string | null;
  websiteReachable: boolean | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<string>;
  name: string;
  roles: Generated<ArrayType<UserRole>>;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  token: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verificationType: VerificationType;
}

export interface DB {
  accessRequests: AccessRequests;
  accounts: Accounts;
  invites: Invites;
  leadQueries: LeadQueries;
  leads: Leads;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
